language: node_js

node_js:
  - "0.12"

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
    - sudo apt-get install -y php5

install:
    - npm install -g mockery
    - npm install -g mock-spawn

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10
