language: node_js

node_js:
  - "0.12"

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
    - sudo apt-get update
    - sudo add-apt-repository -y ppa:ondrej/php5-5.6
    - sudo apt-get install -y php5-cli
    - sudo php -v

install:
    - npm install -g mockery
    - npm install -g mock-spawn

script: 'curl -s https://raw.githubusercontent.com/vinicarlos56/ci/master/build-package.sh | sh'

git:
  depth: 10
